### ISSUE TITLE
Is there any way to use this without root?

### ISSUE THREAD

**Issue by i30817** [vaeth/squashmount#5]
That is i want to make it possible to mount (one at a time, it's for dosbox compressed games) a fuse union filesystem that joins a normal persistent directory (for saves and config files per each game) and a squashfs image (for the games). Then i want to incorporate this into the linux version of some frontend.

However, requiring root for every mount and umount  of the games is a major turn off, considering the user owns all of them (they're in the home dir). Is there anyway to avoid this?

**Comment by vaeth** [comment]
I do not think there is a reasonable way around being root for this script: After all, for executing the umount on shutdown, it is necessary to read the mounted data, and it would be a security risk to let some user write there. (Not to speak that also most mount/umount commands also require root permissions for a reason.)

What I would do in your case is to replace the first line by "#!/usr/bin/perl" (this is automatic if you install from the mv overlay) and create sudo rules by allowing
/usr/bin/squashmount stop|start [user's mountpoint]
to be executed as root by the user (with the usual restrictions of sudo of cleaning the environment etc.) without a password. Unless squashmount has a serious bug, this should be reasonably safe.

**Comment by i30817** [comment]
Mmm, i'm going to use a homegrown solution of fuse-unionfs and [squashfuse](https://github.com/vasi/squashfuse). Speed is not ultra important for dosgames and there are very few writable files in games anyway and they tend to be config or saves anyway.

It's a pity that overlay requires root thou.

**Comment by vaeth** [comment]
Since squashmount v15.0.0 there is now the possibility to use squashfuse instead of squashfs.

If combined with unionfs-fuse , adapted location for /etc/squashmount.pl and /run/squashmount, and adapted defaults for the options, it is then possible to use squashmount in user mode.

The new switch --user makes all corresponding changes ('though one can still override particular ones, of course).

Thus, I consider this bug now as closed. (I did not do too serious tests for user mode, 'though. Please open a new bug if you run into problems.)
