### ISSUE TITLE
MemoryDenyWriteExecute option not met

### ISSUE THREAD

**Issue by Arnaudv6** [vaeth/squashmount#7]
Hello, when bumping to last version,
I get journalctl reporting this error :

`août 10 19:52:23 Gentoo-2600k systemd[1]: [/usr/lib64/systemd/system/squashmount.service:14] Unknown lvalue 'MemoryDenyWriteExecute' in section 'Service`

I guess this option was added to a systemd version I don't have yet.
I commented the option in service file and it seems to work fine...
Still I expect ebuild should require said systemd version, or adapt...

Thanks for you soft : I have been hapilly using it up untill now !

**Comment by Arnaudv6** [comment]
Not so good indeed :

# systemctl status squashmount.service 
● squashmount.service - mount/umount all squashmount configured mount points
   Loaded: loaded (/usr/lib64/systemd/system/squashmount.service; enabled; vendor preset: disabled)
  Drop-In: /etc/systemd/system/squashmount.service.d
           └─timeout.conf
   Active: active (exited) since mer. 2016-08-10 20:20:10 CEST; 6s ago
  Process: 1108 ExecStart=/usr/bin/squashmount start (code=exited, status=0/SUCCESS)
 Main PID: 1108 (code=exited, status=0/SUCCESS)

août 10 20:20:09 Gentoo-2600k systemd[1]: Starting mount/umount all squashmount configured mount points...
août 10 20:20:10 Gentoo-2600k squashmount[1108]: * [kernel]:  mounting...
août 10 20:20:10 Gentoo-2600k squashmount[1108]: * [kernel]:  error:   squashfuse_ll, squashfuse not found in $PATH
août 10 20:20:10 Gentoo-2600k squashmount[1108]: * [kernel]:  warning: squashfuse failed
août 10 20:20:10 Gentoo-2600k squashmount[1108]: * [kernel]:  error:   failed to mount squash-file
août 10 20:20:10 Gentoo-2600k squashmount[1108]: * [portage]: mounting...
août 10 20:20:10 Gentoo-2600k squashmount[1108]: * [portage]: error:   squashfuse_ll, squashfuse not found in $PATH
août 10 20:20:10 Gentoo-2600k squashmount[1108]: * [portage]: warning: squashfuse failed
août 10 20:20:10 Gentoo-2600k squashmount[1108]: * [portage]: error:   failed to mount squash-file
août 10 20:20:10 Gentoo-2600k systemd[1]: Started mount/umount all squashmount configured mount points.

**Comment by Arnaudv6** [comment]
Sorry for fonts and layout in previous post :
I trid putting it in "code" or "quote" tags to no avail....

**Comment by vaeth** [comment]
Concerning the first issue, I am not sure what to do: This should be just a warning, isn't it? Or is mounting really prevented only because of an unknown option? Is systemd really **that** stupid that it completely refuses to work with service files for possibly higher versions?

The other thing is strange: Unless you set @squashorder or pass --user or --squashorder, squashfuse will only be attempted as a fallback if mounting fails. This is tested in several setups. Are you sure that you did none of these 3 things? If yes, what happens if you pass the option -vvv to the mounting squashmount command.

**Comment by Arnaudv6** [comment]
Thanks for your answer Vaeth,

journalctl I call with -p4 switch... I guess I will learn to ignore this line together with the -supposedly harmless- ACPI errors I get each boot.

> Unless you set @squashorder or pass --user or --squashorder, squashfuse will only be attempted as a fallback if mounting fails.

I did nothing of the sort AFAIR. But I have a heavily stripped down squashmount.pl : maybe it is not so very robust and it broke at upgrade. I'll try and check as soon as I get home.

**Comment by vaeth** [comment]
If your squashmount.pl contains no secrets, it might be helpful if you post it.
In any case, the output of squashmount start with the very verbose options -vvv might be useful

**Comment by Arnaudv6** [comment]
I have no secret indeed: here is my [squashmount.pl](http://arnaudv6.free.fr/upload/squashmount_pl)
Please don't invest too much energy in it: I did not dig the problem, barely did I read the logs.
I'll soon post verbose start errors.

**Comment by vaeth** [comment]
I don't see anything suspicious in you config which might cause the problem.
Let's hope that the -vvv will give more information about the mysterious behaviour.

**Comment by albel727** [comment]
While the bug summary actually **IS** a harmless warning, the real problem that affects both of us lies in CapabilityBoundingSet, [this systemd bug](https://github.com/systemd/systemd/issues/1221), and the fact that current stable Gentoo has lower systemd version than the one it was fixed in.

As per the bug, the fact that you use several lines starting with empty assignment means that the service is given **NO CAPABILITIES AT ALL**, and stuff fails without necessary permissions. I haven't tested on a newer systemd, but on the buggy one, this oneliner works:

`CapabilityBoundingSet=CAP_CHOWN CAP_DAC_OVERRIDE CAP_SYS_ADMIN CAP_SYS_MODULE`

Surrepticiously adding `ExecStartPre=/usr/bin/captest --text` to the unit shows that, indeed, the caps are limited exactly to that.

Note, however, that compared to what you already have in there, an additional capability, **CAP_DAC_OVERRIDE**, is actually **REQUIRED** for the unit, or the service is **UNABLE** to check, squash and remove user-private (e.g. rwx------) files/directories in `changes` directories.

**Comment by vaeth** [comment]
So I suppose that using the 2 lines
````
CapabilityBoundingSet=
CapabilityBoundingSet=CAP_CHOWN CAP_DAC_OVERRIDE CAP_SYS_ADMIN CAP_SYS_MODULE
````
should work with all systemd versions (except for the warning on older ones) and should also match the documentation to not set anything else than the above 4 capabilities?

**Comment by albel727** [comment]
No. If you use more than one line, it fails for the reasons I explained above. I've tested it anyway, but no, the empty line removes all caps and nothing can restore them afterwards. Are you sure you even need empty line? In your place, I'd see what captest run from the unit would tell you without it.

**Comment by vaeth** [comment]
Finally there's a few minutes  time...
I took your suggested code now (untested, because I do not use systemd anymore.)

**Comment by Arnaudv6** [comment]
I did not test the patch yet, nor did I find time to investigate or even confirm albel727's developpement of the bug I reported... But thanks a lot for digging this.
